--SELECIONAR TODAS AS TAREFAS
SELECT * FROM TB_TASKS;


--INSERIR UMA NOVA TAREFA
INSERT INTO TB_TASKS (DS_TAREFA, NR_ORDEM, BT_FINALIZADO, DT_CADASTRO)
		VALUES (?, ?, ?, ?);
        

--SELECIONAR TODAS AS TAREFAS FINALIZADAS
SELECT * FROM TB_TASKS
WHERE BT_FINALIZADO = 1;


--ALTERAR ALGUMA TAREFA
UPDATE TB_TASKS
SET DS_TAREFA = 'CAGAR DNV',
	NR_ORDEM= 1,
    BT_FINALIZADO= 0,
    DT_CADASTRO = '2023,04,24'
WHERE ID_TAREFA=4;


--APAGAR ALGUMA TAREFA
DELETE FROM TB_TASKS
WHERE ID_TAREFA = 4;